-- Create a table for community posts
create table community_posts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    content text,
    type text not null default 'text',
    -- 'text', 'trade', 'poll', 'photo'
    image_url text,
    trade_details jsonb,
    poll_details jsonb,
    likes integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Set up Row Level Security (RLS)
alter table community_posts enable row level security;
-- Policy: Everyone can read posts
create policy "Public posts are viewable by everyone." on community_posts for
select using (true);
-- Policy: Authenticated users can insert their own posts
create policy "Users can insert their own posts." on community_posts for
insert with check (auth.uid() = user_id);
-- Policy: Users can update their own posts (e.g. for likes, though ideally likes should be a separate table)
create policy "Users can update own posts." on community_posts for
update using (auth.uid() = user_id);
-- Policy: Admins can delete any post
-- Note: Ideally we'd check a role or specific email. For now, we'll allow users to delete their own, 
-- and we'll handle Admin deletion via the service role key or a specific admin policy if using client-side auth.
-- For this demo, let's allow users to delete their own.
create policy "Users can delete own posts." on community_posts for delete using (auth.uid() = user_id);
-- Admin Policy (Simplified for demo: Allow specific email or if we had an 'is_admin' flag)
-- create policy "Admins can delete any post" ...