-- Create a table for public profiles
create table profiles (
    id uuid references auth.users not null primary key,
    email text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Set up Row Level Security (RLS)
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for
select using (true);
create policy "Users can insert their own profile." on profiles for
insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for
update using (auth.uid() = id);
-- Create a trigger to automatically create a profile entry when a new user signs up
create or replace function public.handle_new_user() returns trigger language plpgsql security definer
set search_path = public as $$ begin
insert into public.profiles (id, email)
values (new.id, new.email);
return new;
end;
$$;
create trigger on_auth_user_created
after
insert on auth.users for each row execute procedure public.handle_new_user();
-- Create a table for analytics events
create table analytics_events (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users,
    event_type text not null,
    -- 'page_view', 'session_start', 'session_end', 'login'
    metadata jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Set up RLS for analytics
alter table analytics_events enable row level security;
-- IMPORTANT: Allow public read access for admin dashboard
-- The admin dashboard uses localStorage-based auth (AdminAuthContext), NOT Supabase auth
-- Therefore auth.uid() is always NULL when admin queries data from the dashboard
-- The dashboard itself is protected by AdminProtectedRoute & AdminAuthContext
create policy "Analytics are viewable by everyone." on analytics_events for
select using (true);
-- Allow anyone to insert analytics events (for tracking page views, sessions, etc.)
create policy "Anyone can insert analytics events." on analytics_events for
insert with check (true);